# Netlify 배포 설정 파일

[build]
  # 이 프로젝트는 빌드 명령어가 필요 없으므로 비워둡니다.
  command = ""
  # 웹사이트 파일들이 있는 위치는 프로젝트 최상위 폴더(root)입니다.
  publish = "."

[[redirects]]
  # 모든 경로의 요청을 index.html로 보내서
  # Single Page Application(SPA) 라우팅이 깨지지 않게 합니다.
  from = "/*"
  to = "/index.html"
  status = 200