# Netlify 빌드 설정을 정의합니다.
[build]
  # 빌드된 정적 파일이 위치한 디렉토리입니다.
  # 이 프로젝트에서는 루트에 index.html이 있으므로 "/"로 설정합니다.
  command = "npm install"  
  publish = "dist"

# Netlify 서버리스 함수에 대한 설정을 정의합니다.
[functions]
  # 함수 소스 코드가 포함된 디렉토리입니다.
  directory = "netlify/functions"
  # 함수를 번들링할 도구를 지정합니다. esbuild가 기본값이며 가장 빠릅니다.
  node_bundler = "esbuild"

# 리디렉션 및 리라이트 규칙을 정의합니다.
# 이 규칙은 Single Page Application (SPA)의 라우팅을 올바르게 처리하기 위해 필수적입니다.
# 정적 파일과 일치하지 않는 모든 요청을 index.html로 보냅니다.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



