[build]
  # 이 명령어가 Netlify에게 서버리스 함수에 필요한 라이브러리(@google/genai, cheerio)를
  # 설치하도록 지시하여 빌드 오류를 해결합니다.
  command = "npm install"
  
  # 프로젝트의 루트 디렉토리를 배포할 정적 사이트로 지정합니다.
  publish = "."
  
  # 서버리스 함수가 위치한 디렉토리를 알려줍니다.
  functions = "netlify/functions"

[functions]
  # Netlify 함수를 번들링할 때 사용할 도구를 지정합니다.
  node_bundler = "esbuild"

[build.environment]
  # 서버리스 함수가 최신 fetch API 등을 안정적으로 사용하도록 Node.js 버전을 지정합니다.
  NODE_VERSION = "20"

# SPA(Single-Page Application)를 위한 리디렉션 규칙입니다.
# 어떤 경로로 접속하든 항상 index.html을 먼저 보여줘서 React가 라우팅을 처리하게 합니다.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
